name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - cartopy
  - plotly
  - geopandas
  - geoplot
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - seaborn
    - plotly
    - ipywidgets
    - bqplot
    - mpld3
    - statsmodels
    - xlrd
